---
version: "2.1"
services:
  mastodon:
    image: lscr.io/linuxserver/mastodon:latest
    container_name: mastodon
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - LOCAL_DOMAIN=lukemilius.com
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_HOST=db
      - DB_USER=mastodon
      - DB_NAME=mastodon
      - DB_PASS=mastodon
      - DB_PORT=5432
      - ES_ENABLED=false
      - SECRET_KEY_BASE=1bc1628d98ee423bda1e526d3e363ed930e7dfd8f13ca9d278c985378dfc3443430ff4d7d92ef23663d39c3f3d6c3146238c5e21b2fe889f62dc59973d0d870e
      - OTP_SECRET=ec19c504ce08ae67d1177b6cad0d71cc6d76818b316c002b356d0a96511fa41b5e94295271399a9b2c218ade9d57bf2b50f8be1b5c7d2db16a224a2a739511e3
      - VAPID_PRIVATE_KEY=Ugv5Hj3JUAZrtDMZJClya4AOabjUNpVw6Yw-u9t-xrc=
      - VAPID_PUBLIC_KEY=BNkwjYjDQA78OOWHL5tkEF6uKMRx6z8LlS1FJj4vZtbvYLO_abcBchfpRBb19s5EuAHCQKnOcdiTojPP18vVgYs=
      - SMTP_SERVER=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_LOGIN=lmiliusnas@gmail.com
      - SMTP_PASSWORD=qyyjudeciwcfrqdr
      - SMTP_FROM_ADDRESS=lmiliusnas@gmail.com
      - S3_ENABLED=false
      - WEB_DOMAIN=social.lukemilius.com #optional
      - ES_HOST=es #optional
      - ES_PORT=9200 #optional
      - ES_USER=elastic #optional
      - ES_PASS=elastic #optional
      # - S3_BUCKET= #optional
      # - AWS_ACCESS_KEY_ID= #optional
      # - AWS_SECRET_ACCESS_KEY= #optional
      # - S3_ALIAS_HOST= #optional
    volumes:
      - ./mastodon/config:/config
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped

  redis:
    restart: always
    image: redis:7-alpine
    networks:
      - internal_network
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
    volumes:
      - ./mastodon/redis:/data

  db:
    restart: always
    image: postgres:14-alpine
    shm_size: 256mb
    networks:
      - internal_network
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
    volumes:
      - ./postgres14:/var/lib/postgresql/data
    environment:
      - 'POSTGRES_USER=mastodon'
      - 'POSTGRES_DB=mastodon'
      - 'POSTGRES_PASSWORD=H3o4q3SoZtR#e!YP@YZ&eS7B'

  es:
    restart: always
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.4
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m -Des.enforce.bootstrap.checks=true"
      - "xpack.license.self_generated.type=basic"
      - "xpack.security.enabled=false"
      - "xpack.watcher.enabled=false"
      - "xpack.graph.enabled=false"
      - "xpack.ml.enabled=false"
      - "bootstrap.memory_lock=true"
      - "cluster.name=es-mastodon"
      - "discovery.type=single-node"
      - "thread_pool.write.queue_size=1000"
      - "ELASTIC_PASSWORD=elastic"
    networks:
       - external_network
       - internal_network
    healthcheck:
       test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
    volumes:
       - ./elasticsearch:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - '127.0.0.1:9200:9200'


networks:
  external_network:
  internal_network:
    internal: true
  