{ pkgs, ... }:

{
  environment.systemPackages = [
    pkgs.autorestic
    pkgs.bitwarden-cli
    pkgs.btop
    pkgs.ctop
    pkgs.curl
    pkgs.dig
    pkgs.docker-compose
    pkgs.diffr
    pkgs.difftastic
    pkgs.dua
    pkgs.duf
    pkgs.dust
    pkgs.git
    pkgs.gparted
    pkgs.htop
    pkgs.inetutils
    pkgs.iotop-c
    pkgs.iperf3
    pkgs.ipmitool
    pkgs.jq
    pkgs.kmon
    pkgs.lazydocker
    pkgs.lshw
    pkgs.nmap
    pkgs.openssl
    pkgs.pciutils
    pkgs.powertop
    pkgs.python314
    pkgs.restic
    pkgs.s-tui
    pkgs.smartmontools
    pkgs.tmux
    pkgs.traceroute
    pkgs.trippy
    pkgs.unzip
    pkgs.usbutils
    pkgs.vim
    pkgs.watch
    pkgs.wget
  ];
}
